---
- name: Checking redis hosts are defined or not
  fail:
    msg: "Playbook execution failed due to missing group"
  when: >
    groups['redis_cluster'] is not defined and
    groups['standalone'] is not defined
