---
- name: Create redis check command without passsword
  set_fact:
    redis_command: redis-cli cluster
  when: redis_password is not defined

- name: Create redis check command with password
  set_fact:
    redis_command: "redis-cli -a {{ redis_password }}"
  when: redis_password is defined

- name: Check Redis Standalone Server status
  command: "{{ redis_command }} ping"
  changed_when: false
  when: inventory_hostname in groups['standalone']

- name: Check Redis Master Server status
  command: "{{ redis_command }} -p {{ master_redis_port }} ping"
  changed_when: false
  when: inventory_hostname in groups['master_nodes']

- name: Check Redis Slave Server status
  command: "{{ redis_command }} -p {{ slave_redis_port }} ping"
  changed_when: false
  when: inventory_hostname in groups['slave_nodes']
