---
- name: Checking Pre-Requisities
  include: check-prerequisities.yml

- name: Configure OS level packages
  include: configure-packages.yml
  when: >
    inventory_hostname in groups['redis_nodes'] or
    inventory_hostname in groups['standalone']

- name: Install and configure redis with common configuration
  include: install-configure.yml
  when: >
    inventory_hostname in groups['redis_nodes'] or
    inventory_hostname in groups['standalone']

- name: Configure standalone Redis Server
  include: standalone.yml
  when: >
    inventory_hostname in groups['standalone']

- name: Configure Redis master
  include: master.yml
  when: >
    inventory_hostname in groups['master_nodes']

- name: Configure Redis master
  include: slave.yml
  when: >
    inventory_hostname in groups['slave_nodes']

- name: Running All Handlers
  meta: flush_handlers

- name: Including Healthcheck tasks
  include: healthcheck.yml

- name: Including playbook to create cluster
  include: create-cluster.yml
  when: >
    inventory_hostname in groups['redis_cluster'] and
    cluster_enabled
